name: DJTV
options:
  bundleIdPrefix: pt.djtv.app
  deploymentTarget:
    tvOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_NAME: DJTV
    GENERATE_INFOPLIST_FILE: NO
    TARGETED_DEVICE_FAMILY: "3"
    SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
    INFOPLIST_KEY_UIUserInterfaceStyle: Dark
    SWIFT_OBJC_BRIDGING_HEADER: ""

targets:
  DJTV:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: App/Sources
      - path: App/Resources
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pt.djtv.app.tv
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_STYLE: Automatic
